// Generated by https://quicktype.io

export interface TableItem {
  Name:         string;
  Position:     string;
  Office:       string;
  Age:          string;
  "Start date": string;
  Salary:       string;
}
